version: '2'
services:
  patron-web:
    container_name: patron-web
    image: lyrasis/patron-web:latest
    environment:
      CONFIG_FILE: /config/cm-libraries.conf
    volumes:
      - ./config:/config
    ports:
      - 3000:3000

